config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/dashboard/likes', to: 'likes#index', as: 'dashboard_likes'

  get 'likes/create' # Do not remove
  get 'likes/destroy' # Do not remove
  resources :likes, only: %i[create destroy]

  get 'user_genres/create' # Do not remove
  get 'user_genres/destroy' # Do not remove
  resources :user_genres, only: %i[create destroy]

  get 'places/genres', to: 'places#genres', as: 'places_genres'
  resources :places, only: %i[index show]

  get '/location', to: 'pages#location', as: 'location'

  get '/tastes', to: 'pages#tastes', as: 'tastes'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :place
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  def index
    if params[:tag].present?
      @likes = Like.joins(place: [place_genres: :genre])
                   .where('genres.name ILIKE ?', "%#{params[:tag]}%")
                   .where(user: current_user)
    else
      @likes = Like.where(user: current_user)
    end
    policy_scope(@likes)
    set_genres

    if params[:tag].present?
      respond_to do |format|
        format.js
      end
    end
  end

  def create
    @place = Place.find(params[:place_id])
    @like = Like.new(place: @place, user: current_user)
    authorize @like
    @like.save
    redirect_to place_path(@place)
  end

  def destroy
    @place = Place.find(params[:place_id])
    @like = Like.find_by(place: @place, user: current_user)
    authorize @like
    @like.destroy
    redirect_to place_path(@place)
  end

  private

  def set_genres
    @genres = Like.where(user: current_user).each_with_object({}) do |like, collection|
      like.place.genres.each do |genre|
        collection[genre.name] = [genre, 0] unless collection.key?(genre.name)
        collection[genre.name][1] += 1
      end
    end
  end
end

app/views/likes/_places.html.erb
<% likes.each_with_index do |like, i| %>
  <% last = :last if i == likes.count - 1 %>
  <%= render "components/likes_card", place: like.place, last: last %>
<% end %>

app/views/likes/index.html.erb
<div class="likes-index">
  <%= render 'components/back_arrow' %>
  <div class="tabs-search">
    <nav>
      <div class="nav nav-pills" id="nav-tab" role="tablist">
        <a class="nav-item nav-link active" id="nav-likes-tab" data-toggle="tab" href="#nav-likes" role="tab" aria-controls="nav-likes" aria-selected="true">Liked places</a>
        <a class="nav-item nav-link" id="nav-tastes-tab" data-toggle="tab" href="#nav-tastes" role="tab" aria-controls="nav-tastes" aria-selected="false">Liked genres</a>
      </div>
    </nav>
  </div>
  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-likes" role="tabpanel" aria-labelledby="nav-likes-tab">
      <div class="likes-container d-flex">
        <label for="tab-1" class="check-with-label"><i class="fas fa-tag"></i><h4>Tags</h4></label>
          <input id="tab-1" name="tabs-two" type="checkbox">
          <div class="tags-filter">
            <div class="all-tags d-flex justify-content-between">
              <%= link_to "All places", dashboard_likes_path %>
              <strong><%= current_user.likes.count %></strong>
            </div>
            <ul>
            <% @genres.each do |genre_name, element|  %>
              <%= link_to dashboard_likes_path(tag: element.first.name), remote: true do %>
                <li class="" style="color: <%= element.first.color_hex %>"><%= element.first.name.capitalize %> <strong><%= element.last %></strong></li>
              <% end %>
            <% end %>
          </ul>
        </div>
        <div class="places-likes">
          <%= render "places", likes: @likes %>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="nav-tastes" role="tabpanel" aria-labelledby="nav-tastes-tab">
      <div class="tastes-dashboard" data-controller="tastes">
        <form action="<%= user_genres_create_path %>"
              data-target="tastes.addForm"
              id="add_user_genre"
              data-remote="true"
              >
              <input type="hidden" name="genre_id" value="genre">
              <input type="hidden" name="user_id" value="<%= current_user.id %>">
              <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        </form>
        <form action="<%= user_genres_destroy_path %>"
              data-target="tastes.removeForm"
              id="remove_user_genre"
              data-remote="true"
              >
              <input type="hidden" name="genre_id" value="genre">
              <input type="hidden" name="user_id" value="<%= current_user.id %>">
              <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        </form>
        <%= render 'components/tastes' %>
        <div class="saved-flash">
          <div class="flash">
            <i class="fas fa-check"></i>
            <p>Saved</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/likes/index.js.erb
document.querySelector(".places-likes").innerHTML = "<%= j render 'places', likes: @likes %>"