config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/dashboard/likes', to: 'likes#index', as: 'dashboard_likes'

  get 'likes/create' # Do not remove
  get 'likes/destroy' # Do not remove
  resources :likes, only: %i[create destroy]

  get 'user_genres/create' # Do not remove
  get 'user_genres/destroy' # Do not remove
  resources :user_genres, only: %i[create destroy]

  get 'places/genres', to: 'places#genres', as: 'places_genres'
  resources :places, only: %i[index show]

  get '/location', to: 'pages#location', as: 'location'

  get '/tastes', to: 'pages#tastes', as: 'tastes'
end

app/models/place.rb
# frozen_string_literal: true

class Place < ApplicationRecord
  geocoded_by :address

  has_many :likes, dependent: :destroy
  has_many :place_genres, dependent: :destroy
  has_many :genres, through: :place_genres
  has_many_attached :photos
  validates :name, :address, presence: true
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/places_controller.rb
# frozen_string_literal: true

class PlacesController < ApplicationController
  after_action :verify_authorized, except: %i[index home genres], unless: :skip_pundit?

  def index
    @query = params[:query].presence || '52 ter Rue des Vinaigriers 75010 Paris'
    @query_coordinates = Geocoder.search(@query).first.coordinates

    place_ids = policy_scope(Place)
                .joins(place_genres: { genre: :user_genres })
                .pluck(:id)

    @places = policy_scope(Place)
              .where(id: place_ids)
              .sort_by { |place| place.distance_to(@query_coordinates, :km) }

    add_markers_on_map
    add_curent_position_on_map
  end

  def show
    @place = Place.find(params[:id])
    @like = Like.where(user: current_user, place: @place).first
    authorize @place
  end

  def genres
    @query_genres = params[:query_genres].split(' ')
    @genres = Genre.where(name: @query_genres.map(&:downcase))
    @places = Place.joins(:place_genres).where(place_genres: { genre_id: @genres.pluck(:id) })

    render layout: false
  end

  private

  def add_markers_on_map
    @markers = @places.map do |place|
      {
        lat: place.latitude,
        lng: place.longitude,
        infoWindow: render_to_string(partial: 'info_window', locals: { place: place }),
        image_url: helpers.asset_url('marker.png')
      }
    end
  end

  def add_curent_position_on_map
    @markers << {
      lat: @query_coordinates.first,
      lng: @query_coordinates.last,
      image_url: helpers.asset_url('marker_own.png')
    }
  end
end

app/views/places/_info_window.html.erb
<%= link_to place_path(place) do  %>
  <div class="img-map" style="background-image: url(<%= cl_image_path(place.photos.first.key) %>)"></div>
  <h2><%= place.name %></h2>
<% end %>

app/views/places/_search_by_genres_tab.html.erb
<% genres = Genre.all.map { |genre| genre.name.capitalize }.join(",") %>
<% colors = Genre.all.map { |genre| genre.color_hex }.join(",") %>
<div class="genres-search"
     data-genres = "<%= genres %>"
     data-colors="<%= colors %>"
     data-target="select2search.genres"
     >
     <form class="genres-search-form"
           action="#"
           data-target="select2search.form"
           >
           <div class="search-bar-all">
             <i class="fas fa-search" data-target="select2search.icon"></i>
             <p class="placeholder-genre-search" data-target="select2search.placeholder">Enter a genre...</p>
             <select id="genres-search-bar-select"
                     class="select2"
                     multiple="multiple"
                     data-target="select2search.input"
                     data-action="select_change@window->select2search#tagChange"
                     >
             </select>
             <input class="search-bar-input"
                    type="hidden"
                    name="genres"
                    id="hidden-select-2"
                    value=""
                    data-target="select2search.searchSelect"
                    >
                    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
           </div>
     </form>
     <div class="genres-search-results" data-target="select2search.results">
     </div>
</div>

app/views/places/_search_by_location_tab.html.erb
<div class="bar-search">
          <% previous_search = params[:query] ? params[:query] : "" %>
          <div><%= render "components/search_bar", value: previous_search %></div>
        </div>
        <div class="display-search">
          <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item">
              <a class="nav-link active"
                 id="list-tab"
                 data-toggle="tab"
                 href="#list"
                 role="tab"
                 aria-controls="list"
                 aria-selected="true"
                 data-action="click->tab-selection#changeTab"
                 data-target="tab-selection.list"
                 >
                 List
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link"
                 id="map-result-tab"
                 data-toggle="tab"
                 href="#map-result"
                 role="tab"
                 aria-controls="map-result"
                 aria-selected="false"
                 data-action="click->tab-selection#changeTab"
                 data-target="tab-selection.map"
                 >
                 Map
              </a>
            </li>
          </ul>
        </div>
        <div class="search-results mb-3">
          <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active"
                 id="list"
                 role="tabpanel"
                 aria-labelledby="list-tab"
                 data-target="tab-selection.tabList"
                 >
                 <div class="places">
                   <div class="title-section">
                     <% loc = params[:query].present? ?  "this address" : "my position" %>
                     <h3 id="near">Near <%= loc %></h3>
                   </div>
                   <% @places.each_with_index do |place, i| %>
                     <% last = :last if i == @places.count - 1 %>
                     <%= render "components/search-card", place: place, last: last %>
                   <% end %>
                 </div>
            </div>
            <div class="tab-pane fade"
                 id="map-result"
                 role="tabpanel"
                 aria-labelledby="map-tab"
                 data-target="tab-selection.tabMap"
                 >
                 <div class="map-results">
                   <div id="map"
                        style="width: 100%; height: 550px;"
                        data-markers="<%= @markers.to_json %>"
                        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
                        data-controller="map"
                        data-action="map_shown@window->map#update"
                        data-target="map.mapElement"
                        data-latitude="<%= @query_coordinates.first %>"
                        data-longitude="<%= @query_coordinates.last %>"
                        >
                   </div>
                 </div>
            </div>
          </div>
        </div>

app/views/places/genres.html.erb
<% if @query_genres.present? %>
  <div class="places">
    <div class="title-section">
      <% if @genres.count <= 2 %>
        <% genres_list = @genres.map {|genre| genre.name.capitalize }.join(" & ") %>
      <% else %>
        <% genres_list = @genres.first(2).map {|genre| genre.name.capitalize }.join(", ") %>
        <% genres_list += " & more" %>
      <% end %>
      <h3>For <%= genres_list %></h3>
    </div>
    <% @places.each_with_index do |place, i| %>
      <% last = :last if i == @places.count - 1 %>
      <%= render "components/search-card", place: place, last: last %>
    <% end %>
  </div>
<% end %>

app/views/places/index.html.erb
<%= render 'components/back_arrow' %>
<div class="places-index"
     data-controller="tab-selection-index">
  <div class="index-container" data-controller="tab-selection">
    <div class="tabs-search">
      <div class="nav nav-pills" id="nav-tab" role="tablist">
        <a class="nav-item nav-link active"
           id="nav-location-tab"
           data-toggle="tab"
           href="#nav-location"
           role="tab"
           aria-controls="nav-location"
           aria-selected="true"
           data-target="tab-selection-index.location"
           data-action="click->tab-selection-index#changeTab"
        >By location</a>
        <a class="nav-item nav-link"
           id="nav-genres-tab"
           data-toggle="tab"
           href="#nav-genres"
           role="tab"
           aria-controls="nav-genres"
           aria-selected="false"
           data-target="tab-selection-index.genres"
           data-action="click->tab-selection-index#changeTab"
        >By genres</a>
      </div>
    </div>

    <div class="tab-content" id="nav-tabContent">
      <div class="tab-pane fade show active"
           id="nav-location"
           role="tabpanel"
           aria-labelledby="nav-location-tab"
           data-target="tab-selection-index.tabLocation"
           >
           <%= render "search_by_location_tab" %>
      </div>
      <div class="tab-pane fade"
           id="nav-genres"
           role="tabpanel"
           aria-labelledby="nav-genres-tab"
           data-controller="select2search"
           data-target="tab-selection-index.tabGenres"
           >
           <%= render "search_by_genres_tab" %>
      </div>
    </div>
  </div>
</div>

app/views/places/show.html.erb
<% require_relative "../../../db/tracks" %>
<% sampled_tracks = TRACKS.sample(8) %>
<div class="show-container">
<%= render 'components/back_arrow' %>
  <div class="carousel-photos">
    <% @place.photos.each do |photo| %>
      <div class="place-photo">
        <%= cl_image_tag photo.key, alt: "photos" %>
      </div>
    <% end %>
  </div>
  <div class="place-details">
    <div class="general-infos">
      <div class="place-name"><h2><%= @place.name %></h2></div>
      <div class="place-like"
           data-controller="likes">
        <form action="<%= likes_create_path(place_id: @place.id) %>"
              data-target="likes.addForm"
              id="add_like"
              data-remote="true"
              >
              <input type="hidden" name="place_id" value="<%= @place.id %>">
              <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        </form>
        <form action="<%= likes_destroy_path(@like) %>"
              data-target="likes.removeForm"
              id="remove_like"
              data-remote="true"
              >
              <input type="hidden" name="like" value=<%= @like.id if @like %>>
              <input type="hidden" name="place_id" value="<%= @place.id %>">
              <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        </form>
        <%= render 'components/tag', background_color:"#49af91", text: "Open", class: "pop-tag selected place-tag-open" %>
        <div class="icon-container"
             data-target="likes.iconContainer">
          <%= icon("far", "heart", { "data-target": "likes.icon",
                                   "data-action": "click->likes#toggleSelection",
                                   "data-liked":  "#{@like.present?}" }) %>
        </div>
      </div>
    </div>
    <div class="place-rating">
      <% if @place.avg_rating % 1 == 0.5 %>
        <% @place.avg_rating.floor.times do %>
          <i class="fas fa-star"></i>
        <% end %>
        <i class="fas fa-star-half-alt"></i>
        <% (5 - @place.avg_rating.ceil).times do %>
          <i class="far fa-star"></i>
        <% end %>
      <% else %>
        <% @round = (@place.avg_rating * 2.0).round / 2.0 %>
        <% if @round % 1 == 0 %>
          <% @round.round.times do %>
            <i class="fas fa-star"></i>
          <% end %>
          <% (5 - @round.round).times do %>
            <i class="far fa-star"></i>
          <% end %>
        <% elsif @round % 1 == 0.5 %>
          <% @round.floor.times do %>
            <i class="fas fa-star"></i>
          <% end %>
          <i class="fas fa-star-half-alt"></i>
          <% (5 - @round.round).times do %>
            <i class="far fa-star"></i>
          <% end %>
        <% end %>
      <% end %>
    </div>



    <div class="place-distance">
      <div class="place-address-distance">
        <p id="show-place-address"><%= @place.address %></p>
      </div>

      <div class="link-map">
        <%= link_to "https://maps.google.com/?q=#{@place.address}", class:"text-decoration-none link-map" do  %>
          <%= icon("fas", "map-marked-alt") %>
        <% end %>
      </div>
    </div>

    <div class="place-tags ">
      <% @place.genres.sort.each do |genre| %>
        <%= render 'components/tag',background_color:"#{genre.color_hex}", text: "#{genre.name.capitalize}" %>
      <% end %>
    </div>

    <div class="place-on-air-bar">
      <h3>On Air previously</h3>
      <div class="place-on-air">
        <div class="place-music">
          <div class="before-music">
            <%= image_tag sampled_tracks[0][:artist_image_url], class:"playing-img" %>
            <p class="playing-artist-name"><%= sampled_tracks[0][:artist_name] %></p>
            <p class="playing-track-name"><%= sampled_tracks[0][:track_name] %></p>
          </div>
          <div class="now-music">
            <%= image_tag sampled_tracks[1][:artist_image_url], class:"playing-img" %>
            <p class="playing-artist-name"><%= sampled_tracks[1][:artist_name] %></p>
            <p class="playing-track-name"><%= sampled_tracks[1][:track_name] %></p>
          </div>
          <div class="next-music">
            <%= image_tag sampled_tracks[2][:artist_image_url], class:"playing-img" %>
            <p class="playing-artist-name"><%= sampled_tracks[2][:artist_name] %></p>
            <p class="playing-track-name"><%= sampled_tracks[2][:track_name] %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="place-top-tracks">
      <h3>Top tracks played</h3>

      <div class="row align-items-center">
        <div class="col-1">
          1
        </div>
        <div class="place-top-tracks-infos col-7">
          <p class="place-top-tracks-title"><%= sampled_tracks[3][:artist_name] %></p>
          <p class="place-top-tracks-group"><%= sampled_tracks[3][:track_name] %></p>
        </div>
        <div class="col">
          <p>Played <%= (170..200).to_a.sample %> times</p>
        </div>
      </div>

      <div class="row align-items-center">
        <div class="col-1">
          2
        </div>
        <div class="place-top-tracks-infos col-7">
          <p class="place-top-tracks-title"><%= sampled_tracks[4][:artist_name] %></p>
          <p class="place-top-tracks-group"><%= sampled_tracks[4][:track_name] %></p>
        </div>
        <div class="col">
          <p>Played <%= (120..170).to_a.sample %> times</p>
        </div>
      </div>

      <div class="row align-items-center">
        <div class="col-1">
          3
        </div>
        <div class="place-top-tracks-infos col-7">
          <p class="place-top-tracks-title"><%= sampled_tracks[5][:artist_name] %></p>
          <p class="place-top-tracks-group"><%= sampled_tracks[5][:track_name] %></p>
        </div>
        <div class="col">
          <p>Played <%= (90..120).to_a.sample %> times</p>
        </div>
      </div>

      <div class="row align-items-center">
        <div class="col-1">
          4
        </div>
        <div class="place-top-tracks-infos col-7">
          <p class="place-top-tracks-title"><%= sampled_tracks[6][:artist_name] %></p>
          <p class="place-top-tracks-group"><%= sampled_tracks[6][:track_name] %></p>
        </div>
        <div class="col">
          <p>Played <%= (50..90).to_a.sample %> times</p>
        </div>
      </div>

      <div class="row align-items-center">
        <div class="col-1">
          5
        </div>
        <div class="place-top-tracks-infos col-7">
          <p class="place-top-tracks-title"><%= sampled_tracks[7][:artist_name] %></p>
          <p class="place-top-tracks-group"><%= sampled_tracks[7][:track_name] %></p>
        </div>
        <div class="col">
          <p>Played <%= (30..50).to_a.sample %> times</p>
        </div>
      </div>

    </div>

    <div class="place-pin-me place-like" data-controller="share">
      <div>
        <h3>Share this place</h3>
      </div>
      <div class="place-pin">
        <% place_genres = @place.genres.map {|genre| genre.name.capitalize }.join(" & ")  %>
        <%= icon("fas", "share-alt", {"data-target": "share.shareButton", "data-action": "click->share#triggerShare", "data-genres": "#{place_genres}"}, "id": "share-icon") %>
      </div>
    </div>

    <div class="place-opening-info">
      <h3 id="opening-infos">Opening infos</h3>
      <div class="green-open"></div>
      <ul class="list-inline text-center">
        <li class="list-inline-item">Mon</li>
        <li class="list-inline-item">Tue</li>
        <li class="list-inline-item">Wed</li>
        <li class="list-inline-item">Thu</li>
        <li class="list-inline-item">Fri</li>
        <li class="list-inline-item">Sat</li>
        <li class="list-inline-item">Sun</li>
      </ul>
    </div>
  </div>
</div>